### ISSUE TITLE
NZB.to Suche mit Passwort

### ISSUE THREAD

**Issue by p00chie** [cytec/SickRage#1]
Wird bei nzb.to eine NZB mit Passwort gesnatched wird das Passwort nicht an sabnzbd über den üblichen Proxy übermittelt.

Hier die URL
http://192.168.1.122:8081/api?ma_password=&apikey=********************************&name=http%3A%2F%2Fcytec.us%2Fnzbto%2Findex.php%3Frel%3DArrow%2BS02E23%2BUnthinkable%2BGERMAN%2BDL%2BDUBBED%2B1080p%2BWebHD%2Bx264-TVP%257B%257B%25C2%25A0usenet-4all.info_aWJLpo37v4tVp24%257D%257D%26user%3Dabcd%26nid%3D1631347%26pass%3D123&cat=serien&mode=addurl&ma_username=

2015-02-13 09:59:33 DEBUG    SEARCHQUEUE-BACKLOG-257655 :: NZB sent to SAB successfully
2015-02-13 09:59:33 DEBUG    SEARCHQUEUE-BACKLOG-257655 :: Result text from SAB: ok

Die nzb befindet sich danach in sabnzbd aber das Passwort (hier usenet-4all.info_aWJLpo37v4tVp24) wird nicht gesetzt.

**Comment by cytec** [comment]
passwort wird übergeben steht auch im filenamen allerdings eben per urlencode

```
http://cytec.us/nzbto/index.php?rel=Arrow S02E23 Unthinkable GERMAN DL DUBBED 1080p WebHD x264-TVP{{usenet-4all.info_aWJLpo37v4tVp24}}&user=abcd&nid=1631347&pass=123&cat=serien&mode=addurl&ma_username=
```

wieso SAB das nicht setzt weiß ich jetzt auch net :/

**Comment by p00chie** [comment]
Scheint nur ein Problem bei SickRage zu sein. Bei deinem SickBeard funktioniert es tadellos.

**Comment by cytec** [comment]
strange, wenn ich dazu komme pack ich mir SAB noch ma drauf und versuch das zu testen :)
Spontan fällt mir da doppen url encode ein :/

**Comment by p00chie** [comment]
Ich habe mal beide nebeneinander gehalten:
SickBeard
http://192.168.1.102:8080/api?nzbname=Arrow+S02E23+Unthinkable+GERMAN+DL+DUBBED+1080p+WebHD+x264-TVP%7B%7Busenet-4all.info_aWJLpo37v4tVp24%7D%7D&ma_password=&apikey=627eb72fa6547750161e787fa0a08b76&name=http%3A%2F%2Fcytec.us%2Fnzbto%2Findex.php%3Frel%3DArrow%2BS02E23%2BUnthinkable%2BGERMAN%2BDL%2BDUBBED%2B1080p%2BWebHD%2Bx264-TVP%257B%257Busenet-4all.info_aWJLpo37v4tVp24%257D%257D%26user%3D1234%26nid%3D1631347%26pass%3D1234&cat=serien&mode=addurl&ma_username=

SickRage
http://192.168.1.102:8080/api?ma_password=&apikey=627eb72fa6547750161e787fa0a08b76&name=http%3A%2F%2Fcytec.us%2Fnzbto%2Findex.php%3Frel%3DArrow%2BS02E23%2BUnthinkable%2BGERMAN%2BDL%2BDUBBED%2B1080p%2BWebHD%2Bx264-TVP%257B%257Busenet-4all.info_aWJLpo37v4tVp24%257D%257D%26user%3D1234%26nid%3D1631347%26pass%3D1234&cat=tv&mode=addurl&ma_username=

Hier sieht man schon ein paar unterschiede. Interessant ist wahrscheinlich nur der Bereich mit der nzb.

Bei der SickBeard übergabe taucht der String:
nzbname=Arrow+S02E23+Unthinkable+GERMAN+DL+DUBBED+1080p+WebHD+x264-TVP%7B%7Busenet-4all.info_aWJLpo37v4tVp24
nochmal Extra auf. Bei der SickRage übergabe fehlt er.

**Comment by p00chie** [comment]
"nzbname" hat mich dann getriggert und hab mal Rage und Beard sab.py verglichen
Bei SickRage fehlt:
    if nzb.resultType == "nzb" and nzb.provider.getID() in ['nzbindex','nzbclub','nzbto']:
        logger.log(u"Pretty name for SAB queue: " + nzb.name)
        params['nzbname'] = nzb.name

**Comment by p00chie** [comment]
Olé ich spring im Kreis damit gehts :smiley:

**Comment by p00chie** [comment]
Zu früh gefreut. Die Passwortübergabe funktioniert.
Allerdings hab ich das jetzt auf meine CuBox gespielt und dabei ist mir erstmal aufgefallen, dass es noch ein Problem mit dem nzbto Provider gibt:

2015-02-14 11:20:53 DEBUG    SEARCHQUEUE-BACKLOG-257655 :: [nzbto] :: _get_title_and_url(), returns (Arrow S02E23 Unthinkable GERMAN DL DUBBED 1080p WebHD x264-TVP{{ usenet-4all.info_aWJLpo37v4tVp24}}, http://cytec.us/nzbto/index.php?rel=Arrow+S02E23+Unthinkable+GERMAN+DL+DUBBED+1080p+WebHD+x264-TVP%7B%7B%C2%A0usenet-4all.info_aWJLpo37v4tVp24%7D%7D&user=*******&nid=1631347&pass=********)

Problem ist hier 
x264-TVP%7B%7B%C2%A0usenet-4all.info_aWJLpo37v4tVp24%7D%7D
%7B%7B%C2%A0 ergibt {{Â&nbsp;

Dadurch steht das Passwort in Sab so:
{{ usenet-4all.info_aWJLpo37v4tVp24}}
Ein verdammtes Leerzeichen nach den geschweiften klammen :cry: 

Hast du irgendeine Ahnung woher das kommen kann oder wie ich das weg bekomme?
Beim Pc taucht das Problem nicht auf

**Comment by p00chie** [comment]
Es scheint so als würde .strip nicht richtig funktionieren.
Habe es damit weg bekommen:
                    p00_test2 = p00_test.decode(encoding='ascii',errors='ignore')
                    logger.log('Password Check3: {{%s}}' %(p00_test2), logger.DEBUG)
                    p00_test3 = strip_non_ascii(p00_test2)
                    logger.log('Password Check4: {{%s}}' %(p00_test3), logger.DEBUG)

def strip_non_ascii(string):
    ''' Returns the string without non ASCII characters'''
    stripped = (c for c in string if 0 < ord(c) < 127)
    return ''.join(stripped)

**Comment by cytec** [comment]
kannst du nen pull request mit den änderungen machen? 
zum development fork bitte, dann bau ich das ein ;)
