### ISSUE TITLE
autoProcessTV - vanished?

### ISSUE THREAD

**Issue by prmths-codes** [cytec/SickRage#14]
Hi,

am I missing something, or why is the autoProcessTV folder vanished entirely?
Im having a hard time here trying to figure out how to get this folder back properly, but I cant find it in the git repo either.

Any comments on that would be appreciated. 

Thanks

**Comment by cytec** [comment]
you can checkout an older version which still has the autoProcessTV folder but i highly recommend switching to nzbToMedia see: https://github.com/SickRage/SickRage/wiki/NZBtoMedia for more details on how to set it up... if you however want to use autoProcessTV you should still be able to use it from the last commit: https://github.com/cytec/SickRage/tree/bfc327700ccea40fd71d065927cb352599aa27d6/autoProcessTV

**Comment by prmths-codes** [comment]
Runs smooth. Thanks for the tip. 
Case closed.
