### ISSUE TITLE
BR Alpha Senderlogo...

### ISSUE THREAD

**Issue by cyablo** [cytec/SickRage#4]
...wird nicht angezeigt. Im Dateinamen befindet sich eine Leerzeile, erwartet wird wohl aber ein "-".

**Comment by neoatomic** [comment]
@cyablo, Wie wird der Name in der Show liste angezeigt.? Kannst du ein Screenshot machen.?

**Comment by cyablo** [comment]
Leider nein, da ich den Dateinamen bei mir schon korrigiert habe. Die Dateien unter images/network haben ja alle Leerzeilen bei getrennten Wörtern, bei BR alpha wird aber die Datei "br-alpha.png" und nicht "br alpha.png" erwartet. Da muss einfach nur das Senderlogo umbenannt werden.

Thetvdb weißt den Sendernamen auch als "BR-alpha" und nicht "BR alpha" aus: http://thetvdb.com/?tab=series&id=79580&lid=14

**Comment by cytec** [comment]
erledigt. sorry hatte ich vergessen ;)

**Comment by cyablo** [comment]
thx :)

**Comment by neoatomic** [comment]
@cytec "br alpha.png" is also a valid network name. :
http://thetvdb.com/index.php?tab=series&id=85021&lid=7 

So by renaming you are removing that logo. :)
